source 'https://rubygems.org'

gem 'middleman', '~> 4.4', '>= 4.4.0'
gem 'middleman-autoprefixer', '~> 2.10', '>= 2.10.1'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
